name: Curl Command Example

on:
  push:
    branches:
      - dev

jobs:
  curl_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Make a GET request
      run: |
        curl --location  'https://api.restful-api.dev/objects/7'
