name: Validate Build Test Package

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  get_main_version:
    runs-on: ubuntu-latest
    outputs:
      ver: ${{steps.step1.outputs.info}}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - id: step1
        run: |
          echo "info="$(mvn org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.version -q -DforceStdout)"" >> "$GITHUB_OUTPUT"

  validate_version:
    needs: get_main_version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: getCurrVersion
        run: |
          echo "currver="$(mvn org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.version -q -DforceStdout)"" >> "$GITHUB_OUTPUT"
          echo working in ${{github.ref}}

      #- Design the logic and Develop the code - to discuss
      - id: validateVersion
        run: |
          chmod +x .github/scripts/validate_version.sh     
          echo "${{needs.get_main_version.outputs.ver}}  \n ${{steps.getCurrVersion.outputs.currver}}"
          echo "info="$(./.github/scripts/validate_version.sh  ${{needs.get_main_version.outputs.ver}} ${{steps.getCurrVersion.outputs.currver}})"" >> "$GITHUB_OUTPUT"
          #echo "info=true" >> "$GITHUB_OUTPUT"

      - name: StopOrContinue
        if: ${{steps.validateVersion.outputs.info == 'false' }}
        uses: actions/github-script@v7.0.1
        with:
          script: |
            core.setFailed('Please update the project version in pom as per the guidelines')
  
  

  build_withTestCases:
    needs: validate_version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          java-version: ' 8.0'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: |
          echo "<settings><interactiveMode>false</interactiveMode><profiles><profile><id>_custom_repositories_</id><activation><activeByDefault>true</activeByDefault></activation><repositories><repository><id>myjfrog</id><name>mycomapny-mvn-release</name><url>https://mycompany.jfrog.io/artifactory/mycompany-mvn-release</url><snapshots><enabled>true</enabled></snapshots></repository></repositories><pluginRepositories/></profile></profiles><servers><server><id>myjfrog</id><username>${{secrets.MYCOMPANY_JFROG_USERNAME}}</username><password>${{secrets.MYCOMPANY_JFROG_PASSWORD}}</password></server></servers><mirrors/><proxies/></settings>" > ~/.m2/settings.xml
          mvn -B clean test --file pom.xml -U        

  build:
    needs: build_withTestCases
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          java-version: ' 8.0'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: |
           echo "<settings><interactiveMode>false</interactiveMode><profiles><profile><id>_custom_repositories_</id><activation><activeByDefault>true</activeByDefault></activation><repositories><repository><id>myjfrog</id><name>mycompany-mvn-release</name><url>https://mycompany.jfrog.io/artifactory/mycompany-mvn-release</url><snapshots><enabled>true</enabled></snapshots></repository></repositories><pluginRepositories/></profile></profiles><servers><server><id>myjfrog</id><username>${{secrets.MYCOMPANY_JFROG_USERNAME}}</username><password>${{secrets.MYCOMPANY_JFROG_PASSWORD}}</password></server></servers><mirrors/><proxies/></settings>" > ~/.m2/settings.xml
          mvn -B clean package --file pom.xml  -DskipTests -U 
          mkdir staging && cp target/*.war staging
      - uses: actions/upload-artifact@v4
        with:
          name: Package
          path: staging
